services:
  app:
    image: frontandstart-app
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    env_file:
      - .docker.env
      - .env
    stdin_open: true
    tmpfs:
      - /app/tmp/pids
    depends_on:
      - postgres
    volumes:
      - ./:/app:c
      - cache:/app/tmp/cache:d
      - bundle:/usr/local/bundle:d
      - node_modules:/app/node_modules:d
      - data:/data:d
    networks:
      backend:
      shared:
        aliases:
          - frontandstart
    healthcheck:
      test: ["CMD", "curl", "http://app:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    command: bin/prod-start.sh

  postgres:
    image: postgres:16.4-bullseye
    container_name: frontandstart-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: 0.0.0.0
    volumes:
      - postgres:/var/lib/postgresql/data:c
    networks:
      backend:
        aliases:
          - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  data:
  cache:

networks:
  backend:
  shared:
    external: true