services:
  app:
    image: frontandstart-app
    build:
      context: .
      target: development
      dockerfile: dockerfile
    env_file:
      - .docker.env
      - .env
    stdin_open: true
    ports:
      - 127.0.0.1:${PORT:-3000}:${PORT:-3000}
    tmpfs:
      - /app/tmp/pids
    depends_on:
      - postgres
      # - redis
    volumes:
      - ./:/app:c
      - cache:/app/tmp/cache:d
      - bundle:/usr/local/bundle:d
      - node_modules:/app/node_modules:d
      - ./data:/data:d
    healthcheck:
      test: ["CMD", "curl", "http://app:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    command: bin/prod-start.sh
