
name: 'Basic docker deploy with compose.prod.yml'

on:
  push:
    branches:
      - main

jobs: 
  build:
    name: Deploy wiht docker compose 
    runs-on: ubuntu-latest
    steps:
      - name: Rebuild docker image
        if: ${{ contains(github.event.head_commit.message, 'rebuild') }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd ~/projects/frontandstart.co
            git pull
            docker compose -f compose.prod.yaml build app

      - name: Pull & restart app container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd ~/projects/frontandstart.co
            git pull
            docker compose -f compose.prod.yaml up --no-deps -d app
